export enum StatusOptions {
  ALIVE = "alive",
  DEAD = "dead",
  UNKNOWN = "unknown",
}

export enum GenderOptions {
  FEMALE = "female",
  MALE = "male",
  UNKNOWN = "unknown",
}

export enum SpeciesOptions {
  HUMAN = "Human",
  ALIEN = "Alien",
  HUMANOID = "Humanoid",
  POOPY_BUTTHOLE = "Poopybutthole",
  MYTHOLOGICAL_CREATURE = "Mythological Creature",
  UNKNOWN = "unknown",
  ANIMAL = "Animal",
  VAMPIRE = "Vampire",
  ROBOT = "Robot",
  PARASITE = "Parasite",
  CRONENBERG = "Cronenberg",
  DISEASE = "Disease",
  PLANET = "Planet",
  GOD = "God",
  DEMENTION = "Dementia",
  MYTHOLOGICAL = "Mythological",
  TIME_GOD = "Time God",
  TELEPATHIC_ALIEN = "Telepathic Alien",
  OMNISCIENT_BEING = "Omniscient being",
  CAT = "Cat",
  DOG = "Dog",
  BIRD_PERSON = "Birdperson",
  SCARY_MONSTER = "Scary Monster",
  CROMULON = "Cromulon",
  SENTIENT_AIRCRAFT = "Sentient aircraft",
  GROMFLOMITE = "Gromflomite",
  GAZORPAZORP = "Gazorpazorp",
  CHICKEN = "Chicken",
  ALIEN_SPAWN = "Alien Spaun",
  AMOEBOID = "Amoeboid",
  CAT_PERSON = "Cat-Person",
  GIANTS = "Giants",
  SNAKE = "Snake",
  BOOBLOBIAN = "Boobloobian",
  LIZARD = "Lizard",
  ELEPHANT_PERSON = "Elephant-Person",
  SENTIENT_PUDDING = "Sentient Pudding",
  SHAPESHIFTER = "Shapeshifter",
  BANANA_PERSON = "Banana-Person",
  CYBORG = "Cyborg",
  SNAIL = "Snail",
  DEMON = "Demon",
  CLARO = "Claro",
  CRAYON_PEOPLE = "Crayon People",
  SOUP = "Soup",
  BUTTER_ROBOT = "Butter Robot",
  SEX_BOT = "Sex Bot",
  MONSTER = "Monster",
  GHOST = "Ghost",
  MINOTAUR = "Minotaur",
  GAME = "Game",
  CLOCK = "Clock",
  FLY = "Fly",
  CELESTIAL = "Celestial",
  ABSTRACT_ENTITY = "Abstract Entity",
  MERPERSON = "Mermaid",
  FANTASY = "Fantasy being",
  QUANTUM_ENTITY = "Quantum Entity",
  SUPER_HUMAN = "Superhuman",
}
